import './styles/menu.css'
import './styles/game.css'

import './scripts/stage'
import './scripts/global'
import './scripts/player'
import './scripts/foods'
import './scripts/enemies'
import './scripts/leaderboard'
import './scripts/chat'
import './scripts/perf-monitor'
import './scripts/gameloop'
import './scripts/event-handlers'
import './scripts/websocket'